[xr.instance]
# std::vector<std::string>
userRequestExtensions = []

[xr.instance.applicationInfo]
# std::string
applicationName = "TinyXrExample"

[xr.system]
# XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY
# XR_FORM_FACTOR_HANDHELD_DISPLAY
formFactor = "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY"

[xr]
# XR_VIEW_CONFIGURATION_TYPE_PRIMARY_MONO
# XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO
# XR_VIEW_CONFIGURATION_TYPE_PRIMARY_QUAD_VARJO
# XR_VIEW_CONFIGURATION_TYPE_SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT
viewConfigType = "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO"

# XR_ENVIRONMENT_BLEND_MODE_OPAQUE
# XR_ENVIRONMENT_BLEND_MODE_ADDITIVE
# XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND
environmentBlendMode = "XR_ENVIRONMENT_BLEND_MODE_OPAQUE"

# both configurations based on: // https://github.com/GodotVR/godot_openxr/blob/master/src/openxr/OpenXRApi.cpp
actionSetsConfig = "./actionSets.json"
interactionProfilesConfig = "./interactionProfiles.json"

# XR_REFERENCE_SPACE_TYPE_VIEW
# XR_REFERENCE_SPACE_TYPE_LOCAL
# XR_REFERENCE_SPACE_TYPE_STAGE
# XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR
# XR_REFERENCE_SPACE_TYPE_UNBOUNDED_MSFT
# XR_REFERENCE_SPACE_TYPE_COMBINED_EYE_VARJO
# XR_REFERENCE_SPACE_TYPE_LOCALIZATION_MAP_ML
# XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT
appSpace = "XR_REFERENCE_SPACE_TYPE_LOCAL"

nearZ = 0.05
farZ = 100.0
