[xr]
# std::vector<std::string>
userRequestExtensions = []

# XR_ENVIRONMENT_BLEND_MODE_OPAQUE
# XR_ENVIRONMENT_BLEND_MODE_ADDITIVE
# XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND
userRequestEnvironmentBlendMode = "XR_ENVIRONMENT_BLEND_MODE_OPAQUE"

# XR_VIEW_CONFIGURATION_TYPE_PRIMARY_MONO
# XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO
# XR_VIEW_CONFIGURATION_TYPE_PRIMARY_QUAD_VARJO
# XR_VIEW_CONFIGURATION_TYPE_SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT
viewConfigType = "XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO"

[xr.applicationInfo]
# std::string
applicationName = "TinyXrTest"
# std::string (Three numbers separated by dots)
applicationVersion = "0.1.0"

[xr.system]
# XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY
# XR_FORM_FACTOR_HANDHELD_DISPLAY
formFactor = "XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY"
